workflow:
  name: 'Staging CI'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - lint
  - build

lint:
  image: node:current
  stage: lint
  script:
    - yarn install --pure-lockfile
    - yarn lint

build:
  image: node:current
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn build
  artifacts:
    paths:
      - ./build
  dependencies:
    - lint
